In [1]:
import os
import sys
os.chdir("../")
sys.path.append(os.getcwd())

In [2]:
import torch
import dgl
from utils import utils
from os.path import join

In [3]:
# g = dgl.graph((
#     [0,0,1,3,4,2],
#     [1,3,4,4,2,0],
# ))
g = dgl.graph((
    [0,1,2,0,3,4],
    [1,2,0,3,4,0],
))

In [4]:
g.edges()

(tensor([0, 1, 2, 0, 3, 4]), tensor([1, 2, 0, 3, 4, 0]))

In [5]:
g.edata['ef'] = torch.randn(g.num_edges(), 2)
g.edata['ef']

tensor([[ 0.2037,  0.7142],
        [-1.0924, -2.1504],
        [-1.2571,  1.6428],
        [-0.1481, -1.9507],
        [-0.7574,  0.4628],
        [ 1.1998, -2.4300]])

In [6]:
g = dgl.remove_edges(g, [0,0,0,0])
g.edata['ef']

tensor([[-1.0924, -2.1504],
        [-1.2571,  1.6428],
        [-0.1481, -1.9507],
        [-0.7574,  0.4628],
        [ 1.1998, -2.4300]])